
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\t\x91V&\xa2I)\xe8[\x94\xa1\x9a\x11\x8d\xb9,'
    
_lr_action_items = {'RPAREN':([2,7,8,9,11,13,15,16,],[-1,11,13,-6,-3,-2,-4,-5,]),'NUMBER':([0,3,4,10,12,],[2,2,2,2,2,]),'LBRACKET':([0,3,4,10,12,],[3,3,3,3,3,]),'COMMA':([2,6,8,9,11,13,15,],[-1,10,12,-6,-3,-2,12,]),'LPAREN':([0,3,4,10,12,],[4,4,4,4,4,]),'RBRACKET':([2,5,6,9,11,13,14,],[-1,9,-7,-6,-3,-2,-8,]),'$end':([1,2,9,11,13,],[0,-1,-6,-3,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'listparams':([3,10,],[5,14,]),'exp':([0,3,4,10,12,],[1,6,8,6,15,]),'tupleparams':([4,12,],[7,16,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> NUMBER','exp',1,'p_exp_number','/Users/immanuel_ben/Desktop/cs262-languages/exam/2.py',44),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_paren','/Users/immanuel_ben/Desktop/cs262-languages/exam/2.py',48),
  ('exp -> LPAREN tupleparams RPAREN','exp',3,'p_exp_tuple','/Users/immanuel_ben/Desktop/cs262-languages/exam/2.py',52),
  ('tupleparams -> exp COMMA exp','tupleparams',3,'p_exp_tupleparams_exp_exp','/Users/immanuel_ben/Desktop/cs262-languages/exam/2.py',56),
  ('tupleparams -> exp COMMA tupleparams','tupleparams',3,'p_exp_tupleparams_exp_tupleparams','/Users/immanuel_ben/Desktop/cs262-languages/exam/2.py',60),
  ('exp -> LBRACKET listparams RBRACKET','exp',3,'p_exp_list','/Users/immanuel_ben/Desktop/cs262-languages/exam/2.py',64),
  ('listparams -> exp','listparams',1,'p_exp_explist_exp','/Users/immanuel_ben/Desktop/cs262-languages/exam/2.py',68),
  ('listparams -> exp COMMA listparams','listparams',3,'p_exp_explist_exp_explist','/Users/immanuel_ben/Desktop/cs262-languages/exam/2.py',72),
]
