
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x0e\xbf\x9e\xb2\x1c\xefA\xe7U\xa9\xfc\xa9\x1e\xbf\xcc\x1c'
    
_lr_action_items = {'FUNCTION':([0,4,12,32,36,],[1,1,-4,-9,-3,]),'LBRACE':([14,17,29,31,],[-18,21,21,21,]),'RETURN':([0,4,12,21,32,33,36,],[7,7,-4,7,-9,7,-3,]),'RBRACE':([21,27,33,37,],[-11,32,-11,-10,]),'SEMICOLON':([2,5,8,14,15,20,22,26,28,32,34,],[-17,12,-18,-18,-15,-14,-12,-16,33,-9,-13,]),'EQUAL':([8,13,],[16,19,]),'ELSE':([22,32,],[29,-9,]),'COMMA':([24,],[30,]),'LPAREN':([10,],[18,]),'VAR':([0,4,12,21,32,33,36,],[6,6,-4,6,-9,6,-3,]),'RPAREN':([18,23,24,25,35,],[-5,-6,-8,31,-7,]),'IDENTIFIER':([0,1,4,6,7,9,12,16,18,19,21,30,32,33,36,],[8,10,8,13,14,14,-4,14,24,14,8,24,-9,8,-3,]),'$end':([0,3,4,11,12,32,36,],[-2,0,-2,-1,-4,-9,-3,]),'IF':([0,4,12,21,32,33,36,],[9,9,-4,9,-9,9,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([21,33,],[27,37,]),'stmt':([0,4,21,33,],[5,5,28,28,]),'element':([0,4,],[4,4,]),'params':([18,30,],[23,35,]),'exp':([0,4,7,9,16,19,21,33,],[2,2,15,17,20,26,2,2,]),'js':([0,4,],[3,11,]),'optparams':([18,],[25,]),'compoundstmt':([17,29,31,],[22,34,36,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> js","S'",1,None,None,None),
  ('js -> element js','js',2,'p_js','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',114),
  ('js -> <empty>','js',0,'p_js_empty','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',117),
  ('element -> FUNCTION IDENTIFIER LPAREN optparams RPAREN compoundstmt','element',6,'p_func_decl','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',126),
  ('element -> stmt SEMICOLON','element',2,'p_statement_el','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',130),
  ('optparams -> <empty>','optparams',0,'p_optparams_empty','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',134),
  ('optparams -> params','optparams',1,'p_optparams','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',138),
  ('params -> IDENTIFIER COMMA params','params',3,'p_params_list','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',142),
  ('params -> IDENTIFIER','params',1,'p_params','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',146),
  ('compoundstmt -> LBRACE statements RBRACE','compoundstmt',3,'p_compound_statement','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',150),
  ('statements -> stmt SEMICOLON statements','statements',3,'p_statements','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',154),
  ('statements -> <empty>','statements',0,'p_statements_empty','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',158),
  ('stmt -> IF exp compoundstmt','stmt',3,'p_if_then_statement','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',162),
  ('stmt -> IF exp compoundstmt ELSE compoundstmt','stmt',5,'p_if_then_else_statement','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',166),
  ('stmt -> IDENTIFIER EQUAL exp','stmt',3,'p_assignment_statement','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',170),
  ('stmt -> RETURN exp','stmt',2,'p_return_statement','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',174),
  ('stmt -> VAR IDENTIFIER EQUAL exp','stmt',4,'p_var_assignment_statement','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',178),
  ('stmt -> exp','stmt',1,'p_exp_statement','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',182),
  ('exp -> IDENTIFIER','exp',1,'p_exp_identifier','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/4.py',191),
]
