
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf1\xf3\x8f\x8e\xaa\xc3S\xd4v\xb4\xa4d\x04\x8b\xea\x19'
    
_lr_action_items = {'FALSE':([0,4,6,11,16,],[1,1,1,1,1,]),'STRING':([0,4,6,11,16,],[2,2,2,2,2,]),'NUMBER':([0,4,6,11,16,],[3,3,3,3,3,]),'COMMA':([1,2,3,7,8,10,12,14,17,],[-5,-3,-2,-1,-4,-6,-7,16,-8,]),'LPAREN':([0,4,6,7,11,16,],[4,4,4,11,4,4,]),'NOT':([0,4,6,11,16,],[6,6,6,6,6,]),'RPAREN':([1,2,3,7,8,9,10,11,12,13,14,15,17,18,],[-5,-3,-2,-1,-4,12,-6,-9,-7,-10,-12,17,-8,-11,]),'IDENTIFIER':([0,4,6,11,16,],[7,7,7,7,7,]),'TRUE':([0,4,6,11,16,],[8,8,8,8,8,]),'$end':([1,2,3,5,7,8,10,12,17,],[-5,-3,-2,0,-1,-4,-6,-7,-8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'args':([11,16,],[13,18,]),'exp':([0,4,6,11,16,],[5,9,10,14,14,]),'optargs':([11,],[15,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> IDENTIFIER','exp',1,'p_exp_identifier','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',127),
  ('exp -> NUMBER','exp',1,'p_exp_number','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',131),
  ('exp -> STRING','exp',1,'p_exp_string','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',135),
  ('exp -> TRUE','exp',1,'p_exp_true','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',139),
  ('exp -> FALSE','exp',1,'p_exp_false','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',143),
  ('exp -> NOT exp','exp',2,'p_exp_not','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',147),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_parens','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',151),
  ('exp -> IDENTIFIER LPAREN optargs RPAREN','exp',4,'p_exp_func_call','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',186),
  ('optargs -> <empty>','optargs',0,'p_optargs_empty','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',190),
  ('optargs -> args','optargs',1,'p_optargs','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',194),
  ('args -> exp COMMA args','args',3,'p_args','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',198),
  ('args -> exp','args',1,'p_args_single','/Users/immanuel_ben/Desktop/cs262-languages/week4/homework/5.py',202),
]
